apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Aleksandr_Akulshin\kompose.exe convert
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: front
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: front
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Aleksandr_Akulshin\kompose.exe convert
        kompose.version: 1.24.0 (7c629530)
      creationTimestamp: null
      labels:
        io.kompose.service: front
    spec:
      containers:
        - image: alexanderakulshin/front_test4minikube
          name: front
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
